### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by jsuceir** [WesleyFreitas472/calculo_sinesp_fipe#1]
está dando erro 
 r = requests.get(f'http://wesleyfreitas472.pythonanywhere.com/teste?ano=2018&modelo=FIAT/SIENA ATTRACT 1.0')
                                                                                                              ^
SyntaxError: invalid syntax

**Comment by WesleyFreitas472** [comment]
Bem observado. O endpoint é /consulta e não /teste.

r = requests.get(f'http://wesleyfreitas472.pythonanywhere.com/consulta/?ano=2018&modelo=FIAT/SIENA ATTRACT 1.0')
